/**
 * Four short full-cast samples for the central /samples landing page.
 *
 * Audio generated by `artifacts/api-server/scripts/generate-editors-picks.mjs`
 * and served from `${API_BASE}/voice-samples/editors-picks/{slug}.mp3`.
 * Cover images live alongside at `/voice-samples/editors-picks/covers/{slug}.webp`.
 *
 * Transcripts here use speaker labels for the UI. Prose source for TTS lives
 * in generate-editors-picks.mjs (do not run sync-transcripts on these four).
 */

export type EditorsPickVoice = "clara" | "kayla" | "maya" | "james" | "theo";
export type EditorsPickPairing =
  | "Her & Him"
  | "Her & Her"
  | "Her & Him & Him";

export interface EditorsPick {
  number: number;
  slug: string;
  title: string;
  tagline: string;
  excerpt: string;
  endsOn: string;
  tags: string[];
  /** Opening narrator — used for voice-strip highlight fallback */
  narrator: EditorsPickVoice;
  /** Every distinct voice in the MP3 */
  cast: EditorsPickVoice[];
  /** Human-readable cast line for cards */
  castLabel: string;
  /** @deprecated alias for narrator — used by legacy call sites */
  voice: EditorsPickVoice;
  voiceName: string;
  voiceMeta: string;
  pairing: EditorsPickPairing;
  runtimeSec: number;
  transcript: string;
}

export function formatRuntime(sec: number): string {
  if (sec < 60) return `~${sec} sec`;
  const m = Math.floor(sec / 60);
  const s = sec % 60;
  return s > 0 ? `~${m}:${String(s).padStart(2, "0")}` : `~${m} min`;
}

export function pickIncludesVoice(
  pick: EditorsPick,
  voice: EditorsPickVoice,
): boolean {
  return pick.cast.includes(voice);
}

export const EDITORS_PICKS: EditorsPick[] = [
  {
    number: 1,
    slug: "02-adjoining-suites",
    title: "The Adjoining Suites",
    tagline: "Two men. One suite. She walked through the connecting door.",
    excerpt:
      "\"One of you holding me still. The other watching until I say his name.\"",
    endsOn: "he says: then get on the bed.",
    tags: ["Full cast", "MFM", "Hotel"],
    narrator: "theo",
    cast: ["theo", "james", "maya"],
    castLabel: "Theo · James · Maya",
    voice: "theo",
    voiceName: "Theo",
    voiceMeta: "British · Measured",
    pairing: "Her & Him & Him",
    runtimeSec: 40,
    transcript: `[Theo] Two men. One hotel suite. She'd had every chance to leave — and walked through the connecting door instead.

[James] We've been talking about you. For months. Tell us what you've imagined.

[Maya] Both of you. In this room. Me between you — and you deciding who goes first.

[James] Be specific.

[Maya] One of you holding me still. The other watching until I say his name.

[James] Look at me. Are you sure?

[Maya] I've never been more sure of anything.

[James] Then get on the bed.`,
  },
  {
    number: 2,
    slug: "09-neighbour",
    title: "The Neighbour",
    tagline: "Three weeks of listening through the floor. Tonight she knocked.",
    excerpt:
      "\"I've been listening to you. I know your rhythm better than I should.\"",
    endsOn: "he says: everything I've been thinking about for three weeks.",
    tags: ["Full cast", "Voyeur", "Neighbours"],
    narrator: "theo",
    cast: ["theo", "james", "maya"],
    castLabel: "Theo · James · Maya",
    voice: "theo",
    voiceName: "Theo",
    voiceMeta: "British · Measured",
    pairing: "Her & Him",
    runtimeSec: 42,
    transcript: `[Theo] Three weeks. Every night — footsteps above her. Barefoot. Restless. Tonight she knocked on his door with an empty wine glass and no shoes.

[Maya] I've been listening to you. The shower. The late nights. I know your rhythm better than I should.

[James] That's a strange thing to admit to your neighbour.

[Maya] I didn't come for the corkscrew. I came because I wanted to know if you've been listening too.

[James] Every night. Every sound you make upstairs.

[Maya] Good. Then tell me what you've been imagining when you hear me.

[James] You. In my kitchen. Not leaving until I—

[Maya] Until you what? Say it.

[James] Until you let me do everything I've been thinking about for three weeks.`,
  },
  {
    number: 3,
    slug: "06-supervisor",
    title: "The Supervisor's Office",
    tagline: "Three years of supervision. Tonight the rule lifts.",
    excerpt:
      "\"Wanting your hands on me. Wanting you to tell me what to do.\"",
    endsOn: "she says: lock the door. Then we'll find out if you mean it.",
    tags: ["Full cast", "Her & Her", "Forbidden"],
    narrator: "clara",
    cast: ["clara", "kayla", "maya"],
    castLabel: "Clara · Kayla · Maya",
    voice: "clara",
    voiceName: "Clara",
    voiceMeta: "British · Soothing",
    pairing: "Her & Her",
    runtimeSec: 38,
    transcript: `[Clara] The report was still open. Neither of them was reading it. Three years of supervision — and tonight, for the first time, the rule didn't apply.

[Maya] You're not looking at the page.

[Kayla] No. I'm looking at you. And I'm done pretending I haven't wanted to for three years.

[Maya] You can't say that. You're still my—

[Kayla] I'm not your supervisor anymore. You passed. You're a doctor now. So tell me — what have you been writing about me in those footnotes?

[Maya] Wanting your hands on me. Wanting you to tell me what to do.

[Kayla] Be still.

[Maya] ...yes.

[Kayla] Lock the door. Then we'll find out if you mean it.`,
  },
  {
    number: 4,
    slug: "08-proposition",
    title: "The Proposition",
    tagline: "A stranger. A room upstairs. Rules before he touches you.",
    excerpt:
      "\"I want you to say it out loud. What you want a stranger to do to you tonight.\"",
    endsOn: "she says: then stop talking — and let me say it.",
    tags: ["Full cast", "Strangers", "Surrender"],
    narrator: "clara",
    cast: ["clara", "james", "maya"],
    castLabel: "Clara · James · Maya",
    voice: "clara",
    voiceName: "Clara",
    voiceMeta: "British · Soothing",
    pairing: "Her & Him",
    runtimeSec: 40,
    transcript: `[Clara] The members' club had no sign on the door. He'd been watching her for an hour. A drink arrived she didn't order — and a message: he asked if he could come over.

[Maya] ...yes.

[James] I'm going to be direct. I have a room upstairs. I won't touch you in the lift. I won't touch you in the corridor. If you change your mind, you walk away — I won't follow.

[Maya] And if I don't?

[James] Then you'll tell me exactly what you want — and I'll decide whether I'm willing to give it to you.

[Maya] You want me to ask.

[James] I want you to say it out loud. What you want a stranger to do to you tonight.

[Maya] Then stop talking — and let me say it.`,
  },
];

/** Voice strip metadata for the mid-page interstitial. */
export const VOICES_META: Array<{
  key: EditorsPickVoice;
  name: string;
  oneLine: string;
}> = [
  {
    key: "maya",
    name: "Maya",
    oneLine: "American. Intimate, close — every reply feels like it's to you.",
  },
  {
    key: "james",
    name: "James",
    oneLine: "British. Direct, confident — the voice in the room with you.",
  },
  {
    key: "kayla",
    name: "Kayla",
    oneLine: "American narrator. Warm, expressive, draws you in.",
  },
  {
    key: "theo",
    name: "Theo",
    oneLine: "British narrator. Sets the scene, then steps back.",
  },
];
