/**
 * Library seed manifest v2 — 30 hand-curated casting intakes.
 * 3 situations per category × 10 categories = 30 library stories.
 *
 * v2 brings: fresher narrative hooks, wider location variety, more
 * pairing diversity (Her & Her in every other category, one Him & Him),
 * and entries fully optimised for the 9-dimension scene diversity system
 * introduced in Task #90.
 *
 * Each entry maps directly to a GenerateStoryRequest that can be passed
 * to planStory() → writeStoryFromBrief() → buildImagePrompts() → generateAllImages().
 * All field values are validated against the same allowlists used by the
 * Casting Room (VALID_MOODS, VALID_INTENSITIES, VALID_CHEMISTRIES, etc.).
 */

export interface SeedEntry {
  situationId: string;
  pairing: string;
  chemistry: string;
  mood: string;
  intensity: string;
  atmosphere: string;
  setting: string;
  country: string;
  city: string;
  whoIsHe: string;
  storyLength: string;
  voiceFeel: string;
  label: string;
}

export const LIBRARY_SEED_MANIFEST: SeedEntry[] = [

  // ── FORBIDDEN & COMPLICATED ─────────────────────────────────────────────────

  {
    situationId: "fc2_01",
    label: "Her client hired her to save his business. She's the only one who can. She wishes she weren't.",
    pairing: "Her & Him",
    chemistry: "She Leads",
    mood: "Forbidden",
    intensity: "Intense",
    atmosphere: "Electric",
    setting: "Casino High-Stakes Room",
    country: "Monaco",
    city: "Monte Carlo",
    whoIsHe: "The Executive",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "fc2_02",
    label: "They have never defined what they are to each other. Tonight someone asks, and neither of them knows what to say.",
    pairing: "Her & Him",
    chemistry: "Push & Pull",
    mood: "Emotional",
    intensity: "Elevated",
    atmosphere: "Foggy",
    setting: "Luxury Hotel",
    country: "Portugal",
    city: "Lisbon",
    whoIsHe: "The Wanderer",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "fc2_03",
    label: "Her colleague's partner has been looking at her differently for weeks. She has been looking back.",
    pairing: "Her & Her",
    chemistry: "Forbidden Pull",
    mood: "Slow Burn",
    intensity: "Warm",
    atmosphere: "Rain",
    setting: "Art Gallery After Hours",
    country: "Netherlands",
    city: "Amsterdam",
    whoIsHe: "The Artist",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── REUNION & RETURN ────────────────────────────────────────────────────────

  {
    situationId: "rr2_01",
    label: "She came to his brother's engagement party intending to say nothing. He found her before the first hour was up.",
    pairing: "Her & Him",
    chemistry: "Slow Surrender",
    mood: "Late Night",
    intensity: "Warm",
    atmosphere: "Firelit",
    setting: "Private Estate",
    country: "Ireland",
    city: "Dublin",
    whoIsHe: "The Old Friend",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "rr2_02",
    label: "They spent a year in the same city and never once spoke. He transferred to her floor last Monday.",
    pairing: "Her & Him",
    chemistry: "Push & Pull",
    mood: "Emotional",
    intensity: "Elevated",
    atmosphere: "Midnight",
    setting: "Penthouse Suite",
    country: "China",
    city: "Hong Kong",
    whoIsHe: "The Detective",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "rr2_03",
    label: "They met on a twelve-day trip when they were twenty-two and lost each other's numbers. She's standing at the bar of a hotel she chose at random.",
    pairing: "Her & Her",
    chemistry: "Playful",
    mood: "First Encounter",
    intensity: "Warm",
    atmosphere: "Golden Hour",
    setting: "Beach House",
    country: "Portugal",
    city: "Algarve",
    whoIsHe: "The Charmer",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── FIRST & UNKNOWN ─────────────────────────────────────────────────────────

  {
    situationId: "fu2_01",
    label: "She read the room number wrong. He opened the door before she knocked.",
    pairing: "Her & Him",
    chemistry: "Nervous Energy",
    mood: "First Encounter",
    intensity: "Subtle",
    atmosphere: "Midnight",
    setting: "Luxury Hotel",
    country: "Japan",
    city: "Kyoto",
    whoIsHe: "The Stranger",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "fu2_02",
    label: "Two men at an opening who've been moving through the same rooms for four hours. Last to leave.",
    pairing: "Him & Him",
    chemistry: "He Takes Charge",
    mood: "Late Night",
    intensity: "Elevated",
    atmosphere: "Electric",
    setting: "Art Gallery After Hours",
    country: "Italy",
    city: "Milan",
    whoIsHe: "The Artist",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "fu2_03",
    label: "She asked him for directions. He was also lost. Neither of them said anything about leaving.",
    pairing: "Her & Him",
    chemistry: "Playful",
    mood: "First Encounter",
    intensity: "Warm",
    atmosphere: "Rain",
    setting: "Late Night City",
    country: "Iceland",
    city: "Reykjavik",
    whoIsHe: "The Funny One",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── POWER & TENSION ─────────────────────────────────────────────────────────

  {
    situationId: "pt2_01",
    label: "He owns the company she's been sent to evaluate. The assessment is due Friday. Tonight is Wednesday.",
    pairing: "Her & Him",
    chemistry: "Power Play",
    mood: "Forbidden",
    intensity: "Intense",
    atmosphere: "Electric",
    setting: "Private Club",
    country: "Germany",
    city: "Berlin",
    whoIsHe: "The Executive",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "pt2_02",
    label: "She drafted every line of this contract. He signed it. Now they're alone and the contract no longer applies.",
    pairing: "Her & Him",
    chemistry: "She Leads",
    mood: "Forbidden",
    intensity: "Elevated",
    atmosphere: "Candlelit",
    setting: "Luxury Hotel",
    country: "Switzerland",
    city: "Geneva",
    whoIsHe: "The Executive",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "pt2_03",
    label: "They run competing agencies. They've been cc'd on every hostile email for eleven months. The conference books them into the same villa.",
    pairing: "Her & Her",
    chemistry: "Rivals",
    mood: "Emotional",
    intensity: "Warm",
    atmosphere: "Sun-Soaked",
    setting: "European Villa",
    country: "Greece",
    city: "Mykonos",
    whoIsHe: "The Executive",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── PSYCHOLOGICAL & OBSESSIVE ───────────────────────────────────────────────

  {
    situationId: "po2_01",
    label: "She saved the last note he left on the shared project board. She's been telling herself she forgot to delete it.",
    pairing: "Her & Him",
    chemistry: "Forbidden Pull",
    mood: "Forbidden",
    intensity: "Elevated",
    atmosphere: "Midnight",
    setting: "Art Gallery After Hours",
    country: "Belgium",
    city: "Brussels",
    whoIsHe: "The Bad One",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "po2_02",
    label: "He has read her correspondence fourteen times. He tells himself it is the argument he is studying, not the way she phrases things.",
    pairing: "Her & Him",
    chemistry: "Slow Surrender",
    mood: "Slow Burn",
    intensity: "Warm",
    atmosphere: "Foggy",
    setting: "Victorian London (1880s)",
    country: "United Kingdom",
    city: "London",
    whoIsHe: "The Detective",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "po2_03",
    label: "She has his number saved under a different name. She has never asked herself why.",
    pairing: "Her & Him",
    chemistry: "He Takes Charge",
    mood: "Late Night",
    intensity: "Elevated",
    atmosphere: "Rain",
    setting: "Late Night City",
    country: "South Korea",
    city: "Seoul",
    whoIsHe: "The Executive",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── CIRCUMSTANCE & PROXIMITY ────────────────────────────────────────────────

  {
    situationId: "cp2_01",
    label: "The flight was cancelled. The hotel had one room left. The attendant said the word 'unfortunately' and looked at both of them.",
    pairing: "Her & Him",
    chemistry: "Nervous Energy",
    mood: "First Encounter",
    intensity: "Warm",
    atmosphere: "Stormy",
    setting: "Mountain Retreat",
    country: "Austria",
    city: "Innsbruck",
    whoIsHe: "The Stranger",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "cp2_02",
    label: "She agreed to house-sit for three weeks. She didn't know he still had a key.",
    pairing: "Her & Him",
    chemistry: "The Best Friend",
    mood: "Emotional",
    intensity: "Warm",
    atmosphere: "Candlelit",
    setting: "Private Estate",
    country: "Portugal",
    city: "Porto",
    whoIsHe: "The Old Friend",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "cp2_03",
    label: "They've been given the same gallery residency for six weeks. The studio has one north-facing window and one easel and they've been pretending this is fine.",
    pairing: "Her & Her",
    chemistry: "Romantic",
    mood: "Tender",
    intensity: "Warm",
    atmosphere: "Golden Hour",
    setting: "Beach House",
    country: "Turkey",
    city: "Bodrum",
    whoIsHe: "The Artist",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── SECRETS & UNSPOKEN ──────────────────────────────────────────────────────

  {
    situationId: "su2_01",
    label: "He's known for three months. He has ten different versions of the sentence. He uses none of them.",
    pairing: "Her & Him",
    chemistry: "Slow Surrender",
    mood: "Emotional",
    intensity: "Warm",
    atmosphere: "Firelit",
    setting: "Art Gallery After Hours",
    country: "Denmark",
    city: "Copenhagen",
    whoIsHe: "The Artist",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "su2_02",
    label: "She has a draft message she's rewritten forty times. He doesn't know it exists.",
    pairing: "Her & Him",
    chemistry: "Push & Pull",
    mood: "Slow Burn",
    intensity: "Elevated",
    atmosphere: "Midnight",
    setting: "Penthouse Suite",
    country: "Netherlands",
    city: "Amsterdam",
    whoIsHe: "The Old Friend",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "su2_03",
    label: "He's told her everything about himself except the one thing that would make all the rest make sense.",
    pairing: "Her & Him",
    chemistry: "He Takes Charge",
    mood: "Late Night",
    intensity: "Elevated",
    atmosphere: "Electric",
    setting: "VIP Suite",
    country: "Japan",
    city: "Tokyo",
    whoIsHe: "The Executive",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── DARK & DANGEROUS ────────────────────────────────────────────────────────

  {
    situationId: "dd2_01",
    label: "She knows what he is. She's known for six months. She has not told anyone. She's not certain which part of that frightens her more.",
    pairing: "Her & Him",
    chemistry: "Power Play",
    mood: "Forbidden",
    intensity: "Intense",
    atmosphere: "Stormy",
    setting: "Private Club",
    country: "Czech Republic",
    city: "Prague",
    whoIsHe: "The Bad One",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "dd2_02",
    label: "He told her to stay away from him. Specifically and clearly. She managed forty-eight hours.",
    pairing: "Her & Him",
    chemistry: "Forbidden Pull",
    mood: "Forbidden",
    intensity: "Elevated",
    atmosphere: "Electric",
    setting: "The Back Room",
    country: "United States",
    city: "Chicago",
    whoIsHe: "The Bad One",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "dd2_03",
    label: "She's building the case that will end his career. He calls her the night before the hearing. She answers.",
    pairing: "Her & Him",
    chemistry: "He Takes Charge",
    mood: "Forbidden",
    intensity: "Elevated",
    atmosphere: "Midnight",
    setting: "Late Night City",
    country: "Mexico",
    city: "Mexico City",
    whoIsHe: "The Detective",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── SLOW BURN & PATIENCE ────────────────────────────────────────────────────

  {
    situationId: "sb2_01",
    label: "She's been his neighbour for two years. He borrowed her umbrella in October. He still hasn't returned it. She hasn't asked.",
    pairing: "Her & Him",
    chemistry: "Slow Surrender",
    mood: "Slow Burn",
    intensity: "Warm",
    atmosphere: "Rain",
    setting: "European Villa",
    country: "France",
    city: "Lyon",
    whoIsHe: "The Old Friend",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "sb2_02",
    label: "Three years of working together and one moment last October she's been building an entire theory around ever since.",
    pairing: "Her & Him",
    chemistry: "Push & Pull",
    mood: "Emotional",
    intensity: "Elevated",
    atmosphere: "Foggy",
    setting: "Mountain Retreat",
    country: "Norway",
    city: "Bergen",
    whoIsHe: "The Professor",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "sb2_03",
    label: "She didn't say it the first summer. She didn't say it the second. This is the third summer and she promised herself.",
    pairing: "Her & Her",
    chemistry: "Lovers",
    mood: "Tender",
    intensity: "Warm",
    atmosphere: "Sun-Soaked",
    setting: "Beach House",
    country: "Croatia",
    city: "Dubrovnik",
    whoIsHe: "The Charmer",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── PROFESSIONAL & CROSSING LINES ───────────────────────────────────────────

  {
    situationId: "pl2_01",
    label: "He's been her client for eight months. The project closes Friday. She has been professional for every one of those eight months.",
    pairing: "Her & Him",
    chemistry: "Power Play",
    mood: "Forbidden",
    intensity: "Elevated",
    atmosphere: "Electric",
    setting: "Penthouse Suite",
    country: "United Arab Emirates",
    city: "Abu Dhabi",
    whoIsHe: "The Executive",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "pl2_02",
    label: "She recommended him for the promotion she should have had. He's bought her a drink every Friday since to feel less guilty. It's been four months.",
    pairing: "Her & Him",
    chemistry: "Rivals",
    mood: "Emotional",
    intensity: "Warm",
    atmosphere: "Candlelit",
    setting: "Private Members Club",
    country: "United Kingdom",
    city: "Edinburgh",
    whoIsHe: "The Detective",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "pl2_03",
    label: "They've been leading the same team in opposing directions for a year. The deadline passes at midnight. Neither of them goes home.",
    pairing: "Her & Him",
    chemistry: "She Leads",
    mood: "Late Night",
    intensity: "Warm",
    atmosphere: "Midnight",
    setting: "Office After Hours",
    country: "Australia",
    city: "Sydney",
    whoIsHe: "The Executive",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
];
