/**
 * Library seed manifest — 30 hand-curated casting intakes.
 * 3 situations per category × 10 categories = 30 library stories.
 *
 * Each entry maps directly to a GenerateStoryRequest that can be passed
 * to planStory() → writeStoryFromBrief() → buildImagePrompts() → generateAllImages().
 * All field values are validated against the same allowlists used by the
 * Casting Room (VALID_MOODS, VALID_INTENSITIES, VALID_CHEMISTRIES, etc.).
 */

export interface SeedEntry {
  situationId: string;
  pairing: string;
  chemistry: string;
  mood: string;
  intensity: string;
  atmosphere: string;
  setting: string;
  country: string;
  city: string;
  whoIsHe: string;
  storyLength: string;
  voiceFeel: string;
  label: string;
}

export const LIBRARY_SEED_MANIFEST: SeedEntry[] = [

  // ── FORBIDDEN & COMPLICATED ─────────────────────────────────────────────────

  {
    situationId: "fc_01",
    label: "She works for him. The attraction is not in the contract.",
    pairing: "Her & Him",
    chemistry: "He Takes Charge",
    mood: "Forbidden",
    intensity: "Elevated",
    atmosphere: "Candlelit",
    setting: "Office After Hours",
    country: "United Kingdom",
    city: "London",
    whoIsHe: "The Executive",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "fc_05",
    label: "They're on opposite sides of a negotiation worth millions.",
    pairing: "Her & Him",
    chemistry: "Rivals",
    mood: "Emotional",
    intensity: "Warm",
    atmosphere: "Electric",
    setting: "Luxury Hotel",
    country: "France",
    city: "Paris",
    whoIsHe: "The Detective",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "fc_08",
    label: "He's her professor. The semester ends in eight weeks.",
    pairing: "Her & Him",
    chemistry: "Slow Surrender",
    mood: "Slow Burn",
    intensity: "Warm",
    atmosphere: "Midnight",
    setting: "Private Estate",
    country: "Italy",
    city: "Florence",
    whoIsHe: "The Professor",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── REUNION & RETURN ────────────────────────────────────────────────────────

  {
    situationId: "rr_05",
    label: "She ends up in his city for one night. He finds out.",
    pairing: "Her & Him",
    chemistry: "Forbidden Pull",
    mood: "Late Night",
    intensity: "Elevated",
    atmosphere: "Rain",
    setting: "Luxury Hotel",
    country: "France",
    city: "Paris",
    whoIsHe: "The Old Friend",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "rr_12",
    label: "She thought he chose someone else. He didn't. Seven years to explain that.",
    pairing: "Her & Him",
    chemistry: "Push & Pull",
    mood: "Emotional",
    intensity: "Elevated",
    atmosphere: "Foggy",
    setting: "Mountain Retreat",
    country: "Scotland",
    city: "Edinburgh",
    whoIsHe: "The Wanderer",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "rr_15",
    label: "They only had one night. She's counted the years. He appears to have counted the same ones.",
    pairing: "Her & Him",
    chemistry: "Slow Surrender",
    mood: "Late Night",
    intensity: "Warm",
    atmosphere: "Firelit",
    setting: "Beach House",
    country: "Greece",
    city: "Santorini",
    whoIsHe: "The Charmer",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── FIRST & UNKNOWN ─────────────────────────────────────────────────────────

  {
    situationId: "fu_01",
    label: "They meet on a delayed flight. Six hours. She tells him things she's never told anyone.",
    pairing: "Her & Him",
    chemistry: "Nervous Energy",
    mood: "First Encounter",
    intensity: "Subtle",
    atmosphere: "Electric",
    setting: "Late Night City",
    country: "Japan",
    city: "Tokyo",
    whoIsHe: "The Stranger",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "fu_04",
    label: "They're the only two people at a party who don't want to be there. Last to leave.",
    pairing: "Her & Him",
    chemistry: "Playful",
    mood: "First Encounter",
    intensity: "Warm",
    atmosphere: "Golden Hour",
    setting: "European Villa",
    country: "Italy",
    city: "Rome",
    whoIsHe: "The Artist",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "fu_13",
    label: "She arrives at a property that's been double-booked. He's already there.",
    pairing: "Her & Her",
    chemistry: "Push & Pull",
    mood: "First Encounter",
    intensity: "Warm",
    atmosphere: "Firelit",
    setting: "Mountain Retreat",
    country: "France",
    city: "Annecy",
    whoIsHe: "The Wanderer",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── POWER & TENSION ─────────────────────────────────────────────────────────

  {
    situationId: "pt_01",
    label: "He has information that could ruin her career. She has information that could end his.",
    pairing: "Her & Him",
    chemistry: "Power Play",
    mood: "Forbidden",
    intensity: "Elevated",
    atmosphere: "Electric",
    setting: "Penthouse Suite",
    country: "United States",
    city: "New York",
    whoIsHe: "The Executive",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "pt_02",
    label: "She works for him and is the only person who isn't intimidated. He finds it unbearable.",
    pairing: "Her & Him",
    chemistry: "He Takes Charge",
    mood: "Forbidden",
    intensity: "Warm",
    atmosphere: "Midnight",
    setting: "Office After Hours",
    country: "United Kingdom",
    city: "London",
    whoIsHe: "The Executive",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "pt_03",
    label: "He has always controlled every room he enters. She is the first exception in fifteen years.",
    pairing: "Her & Him",
    chemistry: "She Leads",
    mood: "Forbidden",
    intensity: "Elevated",
    atmosphere: "Candlelit",
    setting: "Private Members Club",
    country: "United Kingdom",
    city: "London",
    whoIsHe: "The Executive",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── PSYCHOLOGICAL & OBSESSIVE ───────────────────────────────────────────────

  {
    situationId: "po_01",
    label: "She has memorised the way he takes his coffee. He hasn't noticed her yet.",
    pairing: "Her & Him",
    chemistry: "Forbidden Pull",
    mood: "Forbidden",
    intensity: "Elevated",
    atmosphere: "Midnight",
    setting: "Private Club",
    country: "France",
    city: "Paris",
    whoIsHe: "The Bad One",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "po_07",
    label: "He rereads her last message every morning. She doesn't know he kept it.",
    pairing: "Her & Him",
    chemistry: "Slow Surrender",
    mood: "Slow Burn",
    intensity: "Warm",
    atmosphere: "Foggy",
    setting: "Victorian London (1880s)",
    country: "United Kingdom",
    city: "London",
    whoIsHe: "The Detective",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "po_13",
    label: "She knows exactly what time he leaves the building. She tells herself it's coincidence.",
    pairing: "Her & Him",
    chemistry: "He Takes Charge",
    mood: "Late Night",
    intensity: "Elevated",
    atmosphere: "Electric",
    setting: "VIP Suite",
    country: "Monaco",
    city: "Monte Carlo",
    whoIsHe: "The Executive",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── CIRCUMSTANCE & PROXIMITY ────────────────────────────────────────────────

  {
    situationId: "cp_01",
    label: "They're stuck sharing a flat she listed, and he accidentally booked.",
    pairing: "Her & Him",
    chemistry: "Nervous Energy",
    mood: "First Encounter",
    intensity: "Warm",
    atmosphere: "Rain",
    setting: "Luxury Hotel",
    country: "United Kingdom",
    city: "Edinburgh",
    whoIsHe: "The Old Friend",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "cp_07",
    label: "He's been driving her to chemo every week for three months. Neither of them has named it.",
    pairing: "Her & Him",
    chemistry: "The Best Friend",
    mood: "Emotional",
    intensity: "Warm",
    atmosphere: "Candlelit",
    setting: "European Villa",
    country: "Italy",
    city: "Tuscany",
    whoIsHe: "The Artist",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "cp_13",
    label: "They've been assigned the same research project for six months. She has twelve pages of notes about him.",
    pairing: "Her & Her",
    chemistry: "Romantic",
    mood: "Tender",
    intensity: "Warm",
    atmosphere: "Sun-Soaked",
    setting: "Beach House",
    country: "Spain",
    city: "Barcelona",
    whoIsHe: "The Professor",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── SECRETS & UNSPOKEN ──────────────────────────────────────────────────────

  {
    situationId: "su_01",
    label: "She knows something about him that he's never told anyone. She's never asked how she knows.",
    pairing: "Her & Him",
    chemistry: "Slow Surrender",
    mood: "Emotional",
    intensity: "Warm",
    atmosphere: "Candlelit",
    setting: "Art Gallery After Hours",
    country: "United Kingdom",
    city: "London",
    whoIsHe: "The Artist",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "su_07",
    label: "He's been keeping a secret that would change how she thinks about everything.",
    pairing: "Her & Him",
    chemistry: "He Takes Charge",
    mood: "Late Night",
    intensity: "Elevated",
    atmosphere: "Midnight",
    setting: "Penthouse Suite",
    country: "United Arab Emirates",
    city: "Dubai",
    whoIsHe: "The Executive",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "su_13",
    label: "She's been in love with him for two years and has told exactly no one.",
    pairing: "Her & Him",
    chemistry: "Push & Pull",
    mood: "Slow Burn",
    intensity: "Warm",
    atmosphere: "Foggy",
    setting: "European Villa",
    country: "France",
    city: "Paris",
    whoIsHe: "The Old Friend",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── DARK & DANGEROUS ────────────────────────────────────────────────────────

  {
    situationId: "dd_01",
    label: "She knows he's dangerous. That's the part she can't stop thinking about.",
    pairing: "Her & Him",
    chemistry: "Power Play",
    mood: "Forbidden",
    intensity: "Intense",
    atmosphere: "Electric",
    setting: "Private Club",
    country: "United Kingdom",
    city: "London",
    whoIsHe: "The Bad One",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "dd_07",
    label: "He's been watching the building from across the street for three nights. She already knows.",
    pairing: "Her & Him",
    chemistry: "He Takes Charge",
    mood: "Forbidden",
    intensity: "Elevated",
    atmosphere: "Midnight",
    setting: "The Back Room",
    country: "United States",
    city: "New York",
    whoIsHe: "The Detective",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "dd_13",
    label: "The evidence points to him. She's the one who buried it.",
    pairing: "Her & Him",
    chemistry: "Forbidden Pull",
    mood: "Forbidden",
    intensity: "Elevated",
    atmosphere: "Stormy",
    setting: "Ski Chalet",
    country: "France",
    city: "Chamonix",
    whoIsHe: "The Wanderer",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── SLOW BURN & PATIENCE ────────────────────────────────────────────────────

  {
    situationId: "sb_01",
    label: "They've been almost but not quite for three years.",
    pairing: "Her & Him",
    chemistry: "Slow Surrender",
    mood: "Slow Burn",
    intensity: "Warm",
    atmosphere: "Golden Hour",
    setting: "Art Gallery After Hours",
    country: "Italy",
    city: "Rome",
    whoIsHe: "The Artist",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "sb_07",
    label: "He has looked at her the same way for eighteen months. She has never looked away.",
    pairing: "Her & Him",
    chemistry: "Nervous Energy",
    mood: "Slow Burn",
    intensity: "Subtle",
    atmosphere: "Rain",
    setting: "Office After Hours",
    country: "United Kingdom",
    city: "London",
    whoIsHe: "The Old Friend",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "sb_13",
    label: "She promised herself she'd wait until she was certain. She's been certain for a year.",
    pairing: "Her & Him",
    chemistry: "Lovers",
    mood: "Tender",
    intensity: "Warm",
    atmosphere: "Sun-Soaked",
    setting: "Beach House",
    country: "Spain",
    city: "Barcelona",
    whoIsHe: "The Charmer",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },

  // ── PROFESSIONAL & CROSSING LINES ───────────────────────────────────────────

  {
    situationId: "pl_01",
    label: "They met in a boardroom. They are not in a boardroom now.",
    pairing: "Her & Him",
    chemistry: "He Takes Charge",
    mood: "Forbidden",
    intensity: "Elevated",
    atmosphere: "Electric",
    setting: "Office After Hours",
    country: "United States",
    city: "New York",
    whoIsHe: "The Executive",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "pl_07",
    label: "She's been his professional equal for two years. One dinner changed the terms.",
    pairing: "Her & Him",
    chemistry: "Rivals",
    mood: "Emotional",
    intensity: "Warm",
    atmosphere: "Candlelit",
    setting: "Luxury Hotel",
    country: "United Kingdom",
    city: "London",
    whoIsHe: "The Detective",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
  {
    situationId: "pl_13",
    label: "The contract ends at midnight. She has seven hours left of not saying it.",
    pairing: "Her & Him",
    chemistry: "Slow Surrender",
    mood: "Late Night",
    intensity: "Warm",
    atmosphere: "Candlelit",
    setting: "European Villa",
    country: "France",
    city: "Paris",
    whoIsHe: "The Artist",
    storyLength: "10 min",
    voiceFeel: "UK Voice",
  },
];
