/** Act IV category slug → image path (generated by generateExpressAct4Images.mjs) */

export const EXPRESS_ACT4_SLUGS: Record<string, string> = {
  "Restraint & BDSM": "restraint-bdsm",
  "Submission & Worship": "submission-worship",
  "Her Dominance": "her-dominance",
  "What does she really want?": "desire-she",
  "What does he really want?": "desire-he",
  "What do they really want?": "desire-they",
  "How do you want to feel?": "feel",
  "Words & Praise": "praise-words",
  "Dark Fantasy": "dark-fantasy",
  "What's between them?": "tension",
  "How do you want it written?": "style-written",
  "What makes this yours?": "yours",
  "Pure Romance": "romance",
  "Praise & Devotion": "devotion",
  "Story Arc & Plot": "plot",
  "Just the Scene": "scene",
  "How does it end?": "ending",
};

export function expressAct4ImagePath(heading: string): string {
  const slug = EXPRESS_ACT4_SLUGS[heading];
  return slug ? `images/express-act4-${slug}.png` : "images/category-explicit_collection.webp";
}

/** Act IV PNGs — Vite public/images in dev, client/images + /api/images in prod */
export function resolveExpressCategoryImage(relativePath: string, baseUrl: string): string {
  const root = baseUrl.replace(/\/$/, "");
  const clean = relativePath.replace(/^\//, "");
  if (relativePath.includes("express-act4-")) {
    const filename = relativePath.replace(/^images\//, "");
    return `${root}/images/${filename}`;
  }
  return `${root}/${clean}`;
}
