/** Per-scenario cover art — distinct erotic imagery, not one image per room */

const SEO = [
  "images/seo-body-candlelit-doorway.webp",
  "images/seo-body-four-poster-bed.webp",
  "images/seo-body-library-at-night.webp",
  "images/seo-body-silk-on-velvet.webp",
  "images/seo-body-rain-on-window.webp",
  "images/seo-body-fireplace-and-wine.webp",
  "images/seo-body-listening-in-silk.webp",
  "images/seo-body-lovers-embrace.webp",
  "images/seo-body-whisper-close.webp",
  "images/seo-body-bedroom-glow.webp",
  "images/seo-body-candlelit-bath.webp",
  "images/seo-body-embrace-window.webp",
  "images/seo-body-shoulder-whisper.webp",
  "images/seo-body-hands-entwined.webp",
  "images/seo-body-dancing-close.webp",
  "images/seo-body-morning-sheets.webp",
  "images/seo-body-spa-two-women.png",
];

const ROOM_POOLS: Record<string, string[]> = {
  power_exchange: [
    "images/chemistry/takes_charge.webp",
    "images/chemistry/power_play.webp",
    "images/chemistry/leads.webp",
    "images/chemistry/worship.webp",
    "images/chemistry/slow_surrender.webp",
    "images/settings/private_club.webp",
    "images/settings/private_members_club.webp",
    "images/settings/vip_suite.webp",
    "images/category-dominant_surrendered.webp",
    "images/energy/executive.webp",
    "images/energy/soldier.webp",
    ...SEO,
  ],
  the_forbidden: [
    "images/chemistry/forbidden_pull.webp",
    "images/settings/office_after_hours.webp",
    "images/settings/late_night_city.webp",
    "images/category-forbidden_desire.webp",
    "images/energy/stranger.webp",
    "images/energy/professor.webp",
    "images/chemistry/rivals.webp",
    "images/settings/rooftop_bar.webp",
    ...SEO,
  ],
  slow_burn: [
    "images/chemistry/romantic.webp",
    "images/chemistry/slow_surrender.webp",
    "images/chemistry/sweet_tender.webp",
    "images/rooms/slow_burn.webp",
    "images/settings/european_villa.webp",
    "images/category-slow_burn.webp",
    "images/category-emotional_desire.webp",
    ...SEO,
  ],
  dark_territory: [
    "images/rooms/dark_territory.webp",
    "images/chemistry/takes_charge.webp",
    "images/settings/vip_suite.webp",
    "images/settings/penthouse_suite.webp",
    "images/category-explicit_collection.webp",
    "images/chemistry/power_play.webp",
    ...SEO,
  ],
  eyes_on_us: [
    "images/settings/art_gallery.webp",
    "images/settings/rooftop_bar.webp",
    "images/settings/penthouse_suite.webp",
    "images/chemistry/forbidden_pull.webp",
    "images/rooms/eyes_on_us.webp",
    ...SEO,
  ],
  more_than_two: [
    "images/rooms/more_than_two.webp",
    "images/chemistry/playful.webp",
    "images/chemistry/equal_tension.webp",
    "images/settings/luxury_hotel.webp",
    "images/settings/vip_suite.webp",
    ...SEO,
  ],
  sweet_and_savage: [
    "images/chemistry/sweet_tender.webp",
    "images/chemistry/push_pull.webp",
    "images/rooms/sweet_and_savage.webp",
    "images/category-late_night.webp",
    ...SEO,
  ],
  the_edge: [
    "images/rooms/the_edge.webp",
    "images/chemistry/rivals.webp",
    "images/chemistry/forbidden_pull.webp",
    "images/energy/detective.webp",
    "images/settings/penthouse_suite.webp",
    ...SEO,
  ],
  in_character: [
    "images/rooms/in_character.webp",
    "images/settings/belle_epoque.webp",
    "images/settings/concert_backstage.webp",
    "images/energy/artist.webp",
    "images/energy/musician.webp",
    "images/category-historical_romance.webp",
    ...SEO,
  ],
  her_power: [
    "images/chemistry/leads.webp",
    "images/chemistry/takes_charge.webp",
    "images/energy/executive.webp",
    "images/seo-body-spa-two-women.png",
    ...SEO,
  ],
  dark_fantasy: [
    "images/category-dark_romance.webp",
    "images/settings/feudal_japan.webp",
    "images/settings/ancient_mediterranean.webp",
    ...SEO,
  ],
  just_the_scene: [
    "images/settings/vip_suite.webp",
    "images/settings/private_club.webp",
    "images/category-late_night.webp",
    ...SEO,
  ],
  all_of_them: [
    "images/chemistry/playful.webp",
    "images/chemistry/equal_tension.webp",
    "images/rooms/more_than_two.webp",
    ...SEO,
  ],
  the_praise_room: [
    "images/chemistry/worship.webp",
    "images/chemistry/sweet_tender.webp",
    ...SEO,
  ],
  novel_arc: [
    "images/category-second_chance.webp",
    "images/category-historical_romance.webp",
    "images/settings/european_villa.webp",
    ...SEO,
  ],
};

/** Curated per-fantasy art — each scenario gets its own visual */
const SCENARIO_IMAGES: Record<string, string> = {
  he_decides: "images/chemistry/takes_charge.webp",
  she_takes_the_reins: "images/chemistry/leads.webp",
  the_contract: "images/settings/private_members_club.webp",
  the_negotiation: "images/chemistry/power_play.webp",
  the_punishment: "images/chemistry/takes_charge.webp",
  owned: "images/chemistry/worship.webp",
  the_lesson: "images/chemistry/slow_surrender.webp",
  the_colleague: "images/express-act4-office-after-hours-mf.webp",
  the_ex: "images/express-act4-penthouse-hotel-mf.webp",
  wrong_room: "images/express-act4-after-gala.webp",
  what_she_shouldnt_want: "images/category-forbidden_desire.webp",
  the_best_friends_brother: "images/express-act4-london-townhouse-mf.webp",
  the_client: "images/energy/executive.webp",
  the_boss: "images/express-act4-office-after-hours-mf.webp",
  finally: "images/chemistry/slow_surrender.webp",
  the_confession: "images/seo-body-whisper-close.webp",
  seven_years: "images/category-second_chance.webp",
  the_long_flight: "images/settings/orient_express.webp",
  the_last_night: "images/seo-body-morning-sheets.webp",
  the_stranger_on_the_train: "images/energy/stranger.webp",
  the_bodyguard: "images/energy/protector.webp",
  historical: "images/category-historical_romance.webp",
  the_artist: "images/energy/artist.webp",
  the_personal_trainer: "images/energy/athlete.webp",
  the_billionaire: "images/express-act4-penthouse-hotel-mf.webp",
  the_detective_scenario: "images/energy/detective.webp",
  the_rival: "images/chemistry/rivals.webp",
  watched: "images/settings/art_gallery.webp",
  the_mirror: "images/express-act4-penthouse-hotel-mf.webp",
  semi_public: "images/settings/rooftop_bar.webp",
  live_performance: "images/settings/concert_backstage.webp",
  the_window: "images/seo-body-embrace-window.webp",
  gentle_then_not: "images/chemistry/sweet_tender.webp",
  ruin_me: "images/chemistry/push_pull.webp",
  after_everything: "images/seo-body-lovers-embrace.webp",
  the_sweet_spot: "images/seo-body-candlelit-bath.webp",
  say_it: "images/seo-body-shoulder-whisper.webp",
  the_other_one: "images/chemistry/playful.webp",
  two_of_him: "images/express-act4-adjoining-suites-mfm.webp",
  her_choosing: "images/chemistry/leads.webp",
  she_invited_someone: "images/chemistry/playful.webp",
  the_weekend: "images/settings/beach_house.webp",
  obsession: "images/rooms/the_edge.webp",
  mind_games: "images/chemistry/rivals.webp",
  the_test: "images/chemistry/push_pull.webp",
  fixation: "images/rooms/the_edge.webp",
  the_arrangement_edge: "images/settings/private_club.webp",
  completely_undone: "images/rooms/dark_territory.webp",
  nothing_off_limits: "images/category-explicit_collection.webp",
  past_midnight: "images/category-late_night.webp",
  claimed: "images/chemistry/takes_charge.webp",
  no_mercy: "images/chemistry/power_play.webp",
  every_limit: "images/settings/vip_suite.webp",
  three_of_them: "images/express-act4-caribbean-mfm.webp",
  the_one_who_sent_others: "images/chemistry/playful.webp",
  the_two_he_brought: "images/express-act4-caribbean-mfm.webp",
  their_terms: "images/chemistry/equal_tension.webp",
  room_end_of_hall: "images/settings/luxury_hotel.webp",
  the_creature: "images/category-dark_romance.webp",
  the_bargain: "images/settings/feudal_japan.webp",
  the_god_noticed: "images/settings/ancient_mediterranean.webp",
  the_dream_wasnt: "images/category-dark_romance.webp",
  every_specific_thing: "images/chemistry/worship.webp",
  the_way_he_said_it: "images/seo-body-whisper-close.webp",
  worship: "images/chemistry/worship.webp",
  out_loud: "images/seo-body-listening-in-silk.webp",
  already: "images/category-late_night.webp",
  the_continuation: "images/seo-body-bedroom-glow.webp",
  scene_two: "images/settings/vip_suite.webp",
  pure: "images/seo-body-four-poster-bed.webp",
  novel_misunderstanding: "images/category-second_chance.webp",
  novel_last_chance: "images/seo-body-rain-on-window.webp",
  novel_return: "images/category-second_chance.webp",
  novel_obstacle: "images/settings/european_villa.webp",
  her_devoted: "images/chemistry/worship.webp",
  her_on_command: "images/chemistry/leads.webp",
  her_all_eyes: "images/settings/art_gallery.webp",
  her_chose_this: "images/chemistry/leads.webp",
  her_terms: "images/chemistry/takes_charge.webp",
  her_kneeling: "images/chemistry/worship.webp",
  her_rules: "images/settings/private_club.webp",
  her_first: "images/chemistry/leads.webp",
};

function hashScenarioId(id: string): number {
  let h = 0;
  for (let i = 0; i < id.length; i++) h = (h * 31 + id.charCodeAt(i)) >>> 0;
  return h;
}

export function getScenarioImagePath(scenarioId: string, roomId: string): string {
  if (SCENARIO_IMAGES[scenarioId]) return SCENARIO_IMAGES[scenarioId];
  const pool = ROOM_POOLS[roomId] ?? SEO;
  return pool[hashScenarioId(scenarioId) % pool.length] ?? "images/rooms/power_exchange.webp";
}

export function getScenarioImage(
  scenarioId: string,
  roomId: string,
  baseUrl: string,
): string {
  return `${baseUrl}${getScenarioImagePath(scenarioId, roomId)}`;
}
